apiVersion: apps/v1
kind: Deployment
metadata:
  name: tooling-deployment
  # namespace: {youtrNamespace}
  namespace: lifedepository
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tooling
  template:
    metadata:
      labels:
        app: tooling
    spec:
      containers:
        - name: tooling
          # change to your iamge name if you rebuilt
          image: jbissett/ubuntutools:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 3000